version: '3.5'
services:
  redis:   
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass xxxxxxxxxxxxxxxxxx --appendonly yes
    ports:
      - 6379:6379
    networks:
      - backend-services-network

  survey-reports-api:
    image: xxxxxxxxxxxxxxxxxxxx
    container_name: survey-reports-api
    restart: always
    depends_on:
      - redis
    ports:
      - 8881:8881
    networks:
      - backend-services-network

networks:
  backend-services-network:
    driver: bridge

     

