survey: 
  port: ":8881"

db: 
  openDriver: "godror"
  connection: 
    "user=\"USERNAME\" 
     password=\"PASS\" 
     connectString=\"1IP:PORT/DB-NAME?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""

rdb:
  address: "127.0.0.1:6379"
  password: "PASS"
  db: 0

token: 
  issuer: "survey"
  secretKey: "secretKey"
